#!/bin/sh

./compute/ensemble ./compute/anderson-spacing 1 > tmp/anderson-spacing.dat

gnuplot -persist << EOD
set xlabel 'energy spacing'
set ylabel 'density'
plot 'tmp/anderson-spacing.dat' with lines
EOD
