#!/bin/sh

./compute/ensemble './bin/c-anderson --states' 2 > tmp/c-anderson-states.dat

gnuplot -persist << EOD
set xlabel 'energy'
set ylabel 'density'
plot 'tmp/c-anderson-states.dat' with lines
EOD
