#!/usr/bin/env python

import numpy as np
from anderson import hamiltonian

ham = hamiltonian(16, 16)
#vals, vecs = np.linalg.eigh(ham)
vals = np.linalg.eigvalsh(ham)
hist = np.histogram(vals, bins=50, normed=True)
offset = (hist[1][1]-hist[1][0])/2.0

for freq, val in zip(hist[0], hist[1][:-1]):
	print('%12g %12g' % (val+offset, freq))
