#!/usr/bin/env python

import numpy as np
from anderson import hamiltonian, ipr

ham = hamiltonian(8, 8)
vals, vecs = np.linalg.eigh(ham)
iprs = ipr(vecs)
for energy, ipr in zip(vals, iprs):
	print('%12g %12g' % (energy, ipr))
