#!/usr/bin/env python

import numpy as np
import math as m
import sys
from graphene import wavevector_energy
import util

# Compute energies
res = 50j
#kx, ky = np.mgrid[-0:7.5:res, -6.5:6.5:res]
kx, ky = np.mgrid[-5:5:res, -5:5:res]
e_conduction = wavevector_energy(kx, ky)
e_valence = wavevector_energy(kx, ky, valence=True)

# Output data
util.save3d(open('tmp/energies.dat', 'w'), kx, ky, (e_conduction, e_valence))
