#!/usr/bin/env python

import sys
import subprocess
import os

# Get command line arguments
if len(sys.argv) < 3:
	print('Usage: %s COMMAND ENSEMBLE' % sys.argv[0])
	sys.exit()
cmd = sys.argv[1]
try:
	ensemble = int(sys.argv[2])
except ValueError:
	print('Ensemble size must be an integer')
	sys.exit()

# Start up the compute commands
procs = []
for i in range(ensemble):
	p = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
	procs.append(p)

# Get data from the processes and compute the average y-values
first = True
xvals = []
yvals = []
for p in procs:
	sout, serr = p.communicate()
	for i, line in enumerate(sout.split(b'\n')):
		parts = line.strip().split()
		if len(parts) >= 2:
			if first:
				xvals.append(float(parts[0]))
				yvals.append(float(parts[1]))
			else:
				yvals[i] += float(parts[1])
	first = False
for i in range(len(yvals)):
	yvals[i] /= ensemble

# Output the new data
for x, y in zip(xvals, yvals):
	print('%12g %12g' % (x, y))
