#!/usr/bin/env python

import numpy as np
import sys
from graphene import wavevector_energy
import util

# Compute energies
res = 1000j
#kx, ky = np.mgrid[-0:7.5:res, -6.5:6.5:res]
rng = 100
kx, ky = np.mgrid[-rng:rng:res, -rng:rng:res]
e_conduction = wavevector_energy(kx, ky)
e_valence = wavevector_energy(kx, ky, valence=True)

# Compute histogram
bincount = 100
merged = np.array([e_conduction, e_valence]).flatten()
hist = np.histogram(merged, bins=bincount, normed=True)
centers = hist[1][:-1] + (hist[1][1]-hist[1][0])/2.0

# Output data
for center, dens in zip(centers, hist[0]):
	print('%12g %12g' % (center, dens))
